name: password_hasher
version: 0.3.1
author: James Ots <code@jamesots.com>
homepage: https://github.com/jamesots/password_hasher
description: Utility for hashing passwords
dependencies:
  crypto: '>=2.0.1 <3.0.0'
  pbkdf2: '>=0.2.0 <0.3.0'
dev_dependencies:
  test: '>=0.12.20+3 <0.13.0'
  mockito: '>=2.0.2 <3.0.0'
